import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "industrial-yellow": "#FFB703",
        "surface-container-low": "#f8f3eb",
        "text-primary": "#2D2D2D",
        "outline-variant": "#e1bfb2",
        "surface-tint": "#a33e00",
        "background": "#fef9f1",
        "on-secondary": "#ffffff",
        "surface-dim": "#ded9d2",
        "on-surface": "#1d1c17",
        "tertiary": "#7a5500",
        "surface": "#fef9f1",
        "on-background": "#1d1c17",
        "tertiary-container": "#996c00",
        "tertiary-fixed-dim": "#ffba27",
        "inverse-on-surface": "#f5f0e8",
        "surface-variant": "#e7e2da",
        "on-tertiary": "#ffffff",
        "primary": "#9f3d00",
        "on-error-container": "#93000a",
        "surface-white": "#FFFFFF",
        "secondary-fixed-dim": "#c8c6c8",
        "surface-container-highest": "#e7e2da",
        "on-tertiary-fixed-variant": "#5e4100",
        "on-primary-container": "#fffbff",
        "on-primary-fixed": "#360f00",
        "on-tertiary-container": "#fffbff",
        "inverse-primary": "#ffb596",
        "surface-container": "#f2ede5",
        "outline": "#8d7165",
        "text-muted": "#6B6B6B",
        "on-tertiary-fixed": "#271900",
        "on-secondary-fixed": "#1b1b1d",
        "on-error": "#ffffff",
        "on-secondary-container": "#636264",
        "secondary-container": "#e2dfe1",
        "primary-fixed-dim": "#ffb596",
        "tertiary-fixed": "#ffdea9",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#474649",
        "error-container": "#ffdad6",
        "inverse-surface": "#32302b",
        "secondary": "#5f5e60",
        "surface-container-high": "#ece8e0",
        "secondary-fixed": "#e4e2e4",
        "primary-fixed": "#ffdbcd",
        "primary-container": "#c74e00",
        "surface-bright": "#fef9f1",
        "on-surface-variant": "#594137",
        "on-primary-fixed-variant": "#7c2e00",
        "gray-750": "#2D2D2D",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "8px",
        "base": "8px",
        "stack-lg": "32px",
        "stack-md": "16px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "container-max": "1280px",
        "gutter": "24px",
      },
      fontFamily: {
        display: ["'Barlow Condensed'", "'Arial Narrow'", "sans-serif"],
        sans: ["'DM Sans'", "system-ui", "sans-serif"],
        "body-sm": ["DM Sans"],
        "label-md": ["DM Sans"],
        "body-lg": ["DM Sans"],
        "headline-lg-mobile": ["Barlow Condensed"],
        "body-md": ["DM Sans"],
        "display-lg": ["Barlow Condensed"],
        "headline-lg": ["Barlow Condensed"],
        "label-bold": ["DM Sans"],
        "headline-md": ["Barlow Condensed"],
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "36px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "0.01em", fontWeight: "700" }],
        "label-bold": ["14px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
};

export default config;
